plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.huawei.agconnect'
    id "androidx.navigation.safeargs.kotlin"
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

android {
    namespace 'com.zubeyirtaruz.quotable'
    compileSdk 33

    buildFeatures{
        dataBinding true
        viewBinding true
    }

    signingConfigs {
        release {
            storeFile file('key.jks')
            keyAlias 'deepzub'
            keyPassword 'Cide.3437'
            storePassword 'Cide.3437'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
            debuggable true
        }
    }

    defaultConfig {
        applicationId "com.zubeyirtaruz.quotable"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.test:core-ktx:1.5.0'
    implementation 'androidx.recyclerview:recyclerview-selection:1.1.0'

    def lifeCycleExtension_Version = '1.1.1'
    def lifecycle_version = '2.6.0-alpha03'
    def hmsNetworkKit_Version = '6.0.7.300'
    def nav_Version = '2.5.3'
    def activity_version = '1.6.1'
    def preferences_Version = '1.2.0'
    def glide_Version = '4.13.2'

    implementation "androidx.navigation:navigation-fragment-ktx:$nav_Version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_Version"

    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"

    implementation "androidx.preference:preference-ktx:$preferences_Version"

    implementation "de.hdodenhof:circleimageview:2.1.0"
    implementation "com.github.bumptech.glide:glide:$glide_Version"

    //activityViewModels
    implementation "androidx.activity:activity-ktx:$activity_version"

    // Use the network request function of Network Kit.
    implementation "com.huawei.hms:network-embedded:$hmsNetworkKit_Version"

    // Kotlinx Serialization(Required for Network Kit)
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1"

    // swipeRefreshLayout
    implementation "androidx.legacy:legacy-support-v4:1.0.0"

    // viewmodelprovider (android.enableJetifier=true)
    implementation "android.arch.lifecycle:extensions:$lifeCycleExtension_Version"

    implementation 'com.huawei.hms:ads:3.4.49.301'
    implementation "com.google.android.gms:play-services-ads:21.3.0"
    implementation 'com.github.Explore-In-HMS:huawei.ads.admob_mediation:2.0.2'

    //implementation 'com.huawei.hms:ads-prime:3.4.55.300'
    //implementation 'com.huawei.hms:ads-lite:13.4.55.300'

    implementation "com.huawei.hms:hianalytics:6.8.0.300"
    implementation "com.huawei.agconnect:agconnect-crash:1.7.3.300"

    implementation "com.huawei.hms:hwid:6.8.0.300"
    implementation 'com.huawei.agconnect:agconnect-core:1.7.3.300'
    implementation 'com.huawei.agconnect:agconnect-auth:1.7.3.300'

    implementation "com.huawei.agconnect:agconnect-storage:1.5.0.100"


    implementation 'com.huawei.agconnect:agconnect-cloud-database:1.5.5.300'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"

    implementation 'com.huawei.hms:ml-computer-vision-ocr:2.0.1.300'

    implementation 'com.huawei.hms:ml-computer-vision-ocr-latin-model:2.0.1.300'

    implementation 'com.huawei.hms:image-vision:1.0.3.304'
    
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0'

}